/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.admin;

import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Hans
 */
public class AdminMainView extends javax.swing.JPanel {

    /**
     * Creates new form AdminPanel
     */
    
    private final CardLayout cardLayout;
    
    public AdminMainView() {
        initComponents();
        
        cardLayout = new CardLayout();
        mainAdminPanel.setLayout(cardLayout);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LateralMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAuditLogs = new javax.swing.JButton();
        btnTicketManagement = new javax.swing.JButton();
        btnTeamManagement = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnUserManagement = new javax.swing.JButton();
        btnRoleManagement = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mainAdminPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(248, 250, 252));
        setForeground(new java.awt.Color(248, 250, 252));
        setPreferredSize(new java.awt.Dimension(1000, 630));

        LateralMenu.setBackground(new java.awt.Color(33, 52, 72));
        LateralMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin panel");

        btnAuditLogs.setBackground(new java.awt.Color(255, 255, 255));
        btnAuditLogs.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAuditLogs.setForeground(new java.awt.Color(0, 0, 0));
        btnAuditLogs.setText("Audit logs");
        btnAuditLogs.setBorder(null);
        btnAuditLogs.setBorderPainted(false);
        btnAuditLogs.setFocusPainted(false);

        btnTicketManagement.setBackground(new java.awt.Color(255, 255, 255));
        btnTicketManagement.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTicketManagement.setForeground(new java.awt.Color(0, 0, 0));
        btnTicketManagement.setText("Ticket Management");
        btnTicketManagement.setBorder(null);
        btnTicketManagement.setBorderPainted(false);
        btnTicketManagement.setFocusPainted(false);

        btnTeamManagement.setBackground(new java.awt.Color(255, 255, 255));
        btnTeamManagement.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTeamManagement.setForeground(new java.awt.Color(0, 0, 0));
        btnTeamManagement.setText("Team Management");
        btnTeamManagement.setBorder(null);
        btnTeamManagement.setBorderPainted(false);
        btnTeamManagement.setFocusPainted(false);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Sign out");
        jButton6.setFocusPainted(false);

        btnUserManagement.setBackground(new java.awt.Color(255, 255, 255));
        btnUserManagement.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUserManagement.setForeground(new java.awt.Color(0, 0, 0));
        btnUserManagement.setText("User Management");
        btnUserManagement.setBorder(null);
        btnUserManagement.setBorderPainted(false);
        btnUserManagement.setFocusPainted(false);

        btnRoleManagement.setBackground(new java.awt.Color(255, 255, 255));
        btnRoleManagement.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRoleManagement.setForeground(new java.awt.Color(0, 0, 0));
        btnRoleManagement.setText("Role Management");
        btnRoleManagement.setBorder(null);
        btnRoleManagement.setBorderPainted(false);
        btnRoleManagement.setFocusPainted(false);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Profile");
        jButton7.setFocusPainted(false);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome to the admin panel ");

        javax.swing.GroupLayout LateralMenuLayout = new javax.swing.GroupLayout(LateralMenu);
        LateralMenu.setLayout(LateralMenuLayout);
        LateralMenuLayout.setHorizontalGroup(
            LateralMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAuditLogs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTeamManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUserManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTicketManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRoleManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LateralMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LateralMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        LateralMenuLayout.setVerticalGroup(
            LateralMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LateralMenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(88, 88, 88)
                .addComponent(btnUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTicketManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTeamManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRoleManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAuditLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(LateralMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(38, 38, 38))
        );

        mainAdminPanel.setBackground(new java.awt.Color(248, 250, 252));
        mainAdminPanel.setForeground(new java.awt.Color(248, 250, 252));
        mainAdminPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LateralMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LateralMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LateralMenu;
    private javax.swing.JButton btnAuditLogs;
    private javax.swing.JButton btnRoleManagement;
    private javax.swing.JButton btnTeamManagement;
    private javax.swing.JButton btnTicketManagement;
    private javax.swing.JButton btnUserManagement;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainAdminPanel;
    // End of variables declaration//GEN-END:variables

    public CardLayout getCardLayout() {
        return cardLayout;
    }

    public JPanel getLateralMenu() {
        return LateralMenu;
    }

    public JPanel getMainAdminPanel() {
        return mainAdminPanel;
    }

    public JButton getBtnAuditLogs() {
        return btnAuditLogs;
    }

    public JButton getBtnRoleManagement() {
        return btnRoleManagement;
    }

    public JButton getBtnTeamManagement() {
        return btnTeamManagement;
    }

    public JButton getBtnTicketManagement() {
        return btnTicketManagement;
    }

    public JButton getBtnUserManagement() {
        return btnUserManagement;
    }
    
    public JButton getBtnSignOut() {
        return jButton6;
    }
}
