/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.technical;

import javax.swing.JButton;

/**
 *
 * @author Hans
 */
public class TechnicalMainView extends javax.swing.JPanel {

    /**
     * Creates new form UserPanel
     */
    public TechnicalMainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSignOut = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 630));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Technical panel");

        btnSignOut.setBackground(new java.awt.Color(255, 255, 255));
        btnSignOut.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSignOut.setForeground(new java.awt.Color(0, 0, 0));
        btnSignOut.setText("Sign Out");
        btnSignOut.setBorder(null);
        btnSignOut.setBorderPainted(false);
        btnSignOut.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignOut)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(btnSignOut)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(227, 227, 227))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton btnSignOut;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnSignOut() {
        return btnSignOut;
    }
}
